### ISSUE TITLE
9.0.0.3 Tasmota devices not backing up

### ISSUE THREAD

**Issue by SirGoodenough** [danmed/TasmoBackupV1#44] opened 2020-10-31 23:39 UTC
I have loaded the Tasmota DEV version 9.0.0.3 in order to test out the Tasmota Integration in 0.117.1.
I have found that devices that are running 9.0.0.3 are not discoverable by TasmoBackup.  I realize 9.0.0.3 is a dev version, but I wanted you to be aware in case there is a change that you will need to react to.

![Screenshot from 2020-10-31 18-31-52](https://user-images.githubusercontent.com/47349533/97792137-4e79e880-1ba8-11eb-91b6-32afb093296b.png)
![Screenshot from 2020-10-31 18-32-14](https://user-images.githubusercontent.com/47349533/97792139-5174d900-1ba8-11eb-99b3-19f9458dfc1e.png)

**Comment by patrickdk77** [comment] 2020-11-01 03:06
It has nothing to do with 9.0.0.3
The issue is likely with recording the mac address now. 

What the erorr message is telling it, It looked to see if there was an existing device for it in the database, it said there wasn't, so it went to add a new one, but adding the new one failed.

Probably have to diagnose this together. Either something is wrong with the db, or it's not matching correctly somehow.

**Comment by patrickdk77** [comment] 2021-02-28 06:28
I'm going close this. There was an issue with HomeAssistant causing problems around this time, if it's still an issue let me know.

**Closed by patrickdk77** 2021-02-28 06:28 UTC
